# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
build_name=MediaPlayer-FABRIC

# Fabric Properties
minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.16.11

# Mod Properties
mod_version=1.0.1
maven_group=me.j0keer
archives_base_name=MediaPlayer
mod_id=media_player
mod_name=Media Player

# Dependencies
fabric_version=0.102.0+1.21
watermedia_version=2.0.75