name: Project Deployment

on: [push]

permissions:
  contents: write  # Necesario para crear/borrar releases y tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build Fabric module
        run: ./gradlew :Fabric:build

      - name: Build Spigot module
        run: ./gradlew :Spigot:build

      - name: Extract version from gradle.properties
        id: get_version
        run: |
          version=$(grep "mod_version" gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "::set-output name=version::$version"

      - name: Delete existing release if it exists
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          
          # Elimina el release si existe
          release_id=$(gh release view "$TAG" --json id -q ".id" || echo "")
          if [ -n "$release_id" ]; then
            echo "Release $TAG found. Deleting..."
            gh release delete "$TAG" -y
          else
            echo "No release found for $TAG."
          fi

          # Elimina el tag si existe
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG found. Deleting..."
            git push origin --delete "$TAG"
          else
            echo "No tag $TAG found."
          fi
        env:
          GH_TOKEN: ${{ secrets.JAVA_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          files: |
            Fabric/build/libs/*.jar
            Spigot/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
